name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   build:
    docker:
      - image: jumperio/vlab-gcc-arm:latest
    steps:
      - checkout
      - run:
          name: install mbed
          command: pip install mbed-cli && mbed config -G ARM_PATH /usr/bin 
      - run:
          name: build
          command: make
      - store_artifacts:
          path: BUILD/
